# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("browser.anchor_color", "#4466FF");
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150322043245");
user_pref("browser.slowStartup.averageTime", 10959);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"webrtc-status-button\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"social-share-button\",\"widget:jid1-AGzBN6dsbJWp3A@jetpack-ReverseColors\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"newElementCount\":0}");
user_pref("browser.visited_color", "#991AFF");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"VimFx@akhodakivskiy.github.com\":{\"version\":\"0.5.17\",\"type\":\"extension\",\"descriptor\":\"/home/psc/firefox.base/profile/extensions/VimFx@akhodakivskiy.github.com.xpi\"},\"jid1-AGzBN6dsbJWp3A@jetpack\":{\"version\":\"0.3.2\",\"type\":\"extension\",\"descriptor\":\"/home/psc/firefox.base/profile/extensions/jid1-AGzBN6dsbJWp3A@jetpack.xpi\"},\"langpack-en-GB@iceweasel.mozilla.org\":{\"version\":\"31.5.3\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-en-GB@iceweasel.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.5.3");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1427188053000,\"rdfTime\":1426999827000},\"langpack-en-GB@iceweasel.mozilla.org\":{\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-en-GB@iceweasel.mozilla.org.xpi\",\"mtime\":1426993358000}}},{\"name\":\"app-profile\",\"addons\":{\"jid1-AGzBN6dsbJWp3A@jetpack\":{\"descriptor\":\"/home/psc/firefox.base/profile/extensions/jid1-AGzBN6dsbJWp3A@jetpack.xpi\",\"mtime\":1424990677000},\"VimFx@akhodakivskiy.github.com\":{\"descriptor\":\"/home/psc/firefox.base/profile/extensions/VimFx@akhodakivskiy.github.com.xpi\",\"mtime\":1424990677000}}}]");
user_pref("extensions.lastAppVersion", "31.5.3");
user_pref("extensions.lastPlatformVersion", "31.5.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.sdk-widget-inserted.widget:jid1-AGzBN6dsbJWp3A@jetpack-ReverseColors", true);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20150322043245");
user_pref("gecko.mstone", "31.5.3");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 26230);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1425672262);
user_pref("toolkit.telemetry.previousBuildID", "20150225065709");
